INSERT INTO roles(name) VALUES('ROLE_CUSTOMER');
INSERT INTO roles(name) VALUES('ROLE_SUPPLIER');
INSERT INTO roles(name) VALUES('ROLE_VIPCUSTOMER');
INSERT INTO roles(name) VALUES('ROLE_PARTNERCOMPANY');
INSERT INTO roles(name) VALUES('ROLE_ADMIN1');
INSERT INTO roles(name) VALUES('ROLE_ADMIN2');